/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';
import {
  RouterHistory,
} from '@stencil/router';


export namespace Components {

  interface RoutedApp {}
  interface RoutedAppAttributes extends StencilHTMLAttributes {}

  interface RoutedPage {
    'history': RouterHistory;
  }
  interface RoutedPageAttributes extends StencilHTMLAttributes {
    'history': RouterHistory;
  }
}

declare global {
  interface StencilElementInterfaces {
    'RoutedApp': Components.RoutedApp;
    'RoutedPage': Components.RoutedPage;
  }

  interface StencilIntrinsicElements {
    'routed-app': Components.RoutedAppAttributes;
    'routed-page': Components.RoutedPageAttributes;
  }


  interface HTMLRoutedAppElement extends Components.RoutedApp, HTMLStencilElement {}
  var HTMLRoutedAppElement: {
    prototype: HTMLRoutedAppElement;
    new (): HTMLRoutedAppElement;
  };

  interface HTMLRoutedPageElement extends Components.RoutedPage, HTMLStencilElement {}
  var HTMLRoutedPageElement: {
    prototype: HTMLRoutedPageElement;
    new (): HTMLRoutedPageElement;
  };

  interface HTMLElementTagNameMap {
    'routed-app': HTMLRoutedAppElement
    'routed-page': HTMLRoutedPageElement
  }

  interface ElementTagNameMap {
    'routed-app': HTMLRoutedAppElement;
    'routed-page': HTMLRoutedPageElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
